### ISSUE TITLE
@Context decorator undefined for property resolvers

### ISSUE THREAD

**Issue by michaelbromley** [nestjs/graphql#191]
## I'm submitting a...

<pre><code>
[x] Regression 
</code></pre>

## Current behavior
Given the following GraphQL resolver:

```ts
@Resolver('SearchResponse')
export class ShopFulltextSearchResolver implements Omit<BaseSearchResolver, 'reindex'> {
    constructor(private fulltextSearchService: FulltextSearchService) {}

    @Query()
    async search(
        @Ctx() ctx: RequestContext,
        @Args() args: SearchQueryArgs,
    ): Promise<Omit<SearchResponse, 'facetValues'>> {
        return this.fulltextSearchService.search(ctx, args.input);
    }

    @ResolveProperty()
    async facetValues(
        @Ctx() ctx: RequestContext,
        @Context() context: any,
    ): Promise<Array<{ facetValue: FacetValue; count: number }>> {
        return this.fulltextSearchService.facetValues(ctx, context.req.body.variables.input);
    }
}
```
* the `search` method resolves a top-level query
* the `facetValues` method resolves a property of the `SearchResponse` type.

The `context` variable is `undefined` in the `facetValues` method.

## Expected behavior
The `context` variable should contain the GraphQL context object, including the underlying express `req` object which I am making use of in the method body.

Note that this worked in Nest **v6.0.2**. After upgrading today to **v6.0.5** it stopped working. Also, the `@Context` decorator appears to work as expected for top-level queries. Only property resolvers are broken.

## Minimal reproduction of the problem with instructions

I put together this repo, which does not *exactly* reproduce the behaviour in my app but is close. In this case, the `context` object is empty, rather than undefined: https://github.com/michaelbromley/nest-issue-191-repro

## Environment

<pre><code>
Nest version: 6.0.5, graphql v6.0.4

**Comment by dislick** [comment]
Today after upgrading to `@nestjs/core@6.0.5` and `@nestjs/graphql@6.0.4` my `@Args` decorators in `@ResolveProperty` stopped working. I assume they rely on the `context` being present and are therefore broken.

**Comment by kamilmysliwiec** [comment]
Could you please check with `@nestjs/graphql@6.0.5`? Thanks for reporting

**Comment by dislick** [comment]
With `@nestjs/graphql@6.0.5` the `@Args` decorator works again. Thanks for the quick response.

**Comment by michaelbromley** [comment]
Just tested with 6.0.5 and it now works 👍

**Comment by JannesV** [comment]
I'm still having this issue. When I'm using a global guard. For some reason in the __resolveType resolver, the context is wrongly resolved. Normally the context is located under args[2]. But when I'm in a the __resolveType it's located under args[1].

```
import { CanActivate, ExecutionContext, UnauthorizedException } from "@nestjs/common";
import { GqlExecutionContext } from "@nestjs/graphql";
import { ErrorMessages } from "src/utils/errorMessages.constant";
import { GraphqlContext } from "../app/contextRetriever/contextRetriever.service";

export class AuthGuard implements CanActivate {

    public async canActivate(context: ExecutionContext): Promise<boolean> {
        const gqlContext = GqlExecutionContext.create(context);

        const ctx: GraphqlContext = gqlContext.getContext();

        if (!ctx.tokenResult) {
            throw new UnauthorizedException(ErrorMessages.authenticationErrors.noValidToken);
        }

        return true;
    }
}

```

Any ideas?

**Comment by JannesV** [comment]
@kamilmysliwiec  Still no update on this?

**Comment by kamilmysliwiec** [comment]
Please, provide a minimal repository which reproduces your issue (and create a separate issue if you can).

**Comment by JannesV** [comment]
> Please, provide a minimal repository which reproduces your issue (and create a separate issue if you can).

Created a new issue for it with a minimal repo. https://github.com/nestjs/graphql/issues/209
