### ISSUE TITLE
Update dependency ts-simple-ast to ts-morph

### ISSUE THREAD

**Issue by danil-z** [nestjs/graphql#121]
## I'm submitting a...

<pre><code>
[ ] Regression 
[ x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead post your question on Stack Overflow.
</code></pre>

## Current behavior

Project fails to build with typescript 3.3.1 due outdated dependency:

node_modules/ts-simple-ast/dist-declarations/ts-simple-ast.d.ts:5210:114 - error TS2744: Type parameter defaults can only referencepreviously declared type parameters.

```
5210 export declare class AssignmentExpression<T extends ts.AssignmentExpression<TOperator> = ts.AssignmentExpression<TOperator>, TOperator extends ts.AssignmentOperatorToken = ts.AssignmentOperatorToken> extends AssignmentExpressionBase<T> {
                                                                                                                      ~~~~~~~~~



```
## Expected behavior

rimraf dist && tsc
should build a project with nest/graphql

## Environment

<pre><code>
Nest version: 5.7.0

 
For Tooling issues:
- Node version: 11.9
- Platform:  Mac

Others:

</code></pre>

**Comment by rhessus** [comment]
I have the same issue :(

**Comment by kamilmysliwiec** [comment]
Should be fixed in 5.5.3
