### ISSUE TITLE
Cannot find module '@as-integrations/express5' error in Fastify setup

### ISSUE THREAD

**Issue by Gamote** [nestjs/graphql#3693]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

We just upgraded to `@nestjs/apollo@^13.2.0` so we can use the Apollo Server v5 introduced by the #3669.

But as soon as we do we get the following error
```
Error: Cannot find module '@as-integrations/express5'
```

We are using the Apollo Server with Fastify and not Express. Are we forced to install '@as-integrations/express5' although we already have `@as-integrations/fastify@^3.0.0`?

Related: 
- https://github.com/apollographql/apollo-server/issues/8142
- https://github.com/apollo-server-integrations/apollo-server-integration-fastify/issues/308

If the issue is upstream, I think we should still address it in a way or another in the `@nestjs/apollo` as the `13.2.0` is a minor release but it breaks all Fastify setups.

### Expected behavior

We expect that after upgrading to `@nestjs/apollo@^13.2.0` from `@nestjs/apollo@^13.1.0`.

### Package version

^13.2.0

### Graphql version

`graphql`: `^13.2.0`
`@nestjs/platform-fastif`: `^11.1.6`

### NestJS version

^11.1.6

### Node.js version

22.10.0

### In which operating systems have you tested?

- [x] macOS
- [ ] Windows
- [ ] Linux

**Comment by Gamote** [comment]
ℹ️ Currently we have fixed it by lazy-loading the `@as-integrations/express5` when `expressMiddleware` is needed.

Patch: [@nestjs-apollo-npm-13.2.0-5494bfced6.patch](https://github.com/user-attachments/files/22646345/%40nestjs-apollo-npm-13.2.0-5494bfced6.patch)
