### ISSUE TITLE
Upgrading from 10.0.18 to 10.0.20 cause peerDep error: Cannot find module 'ts-morph'

### ISSUE THREAD

**Issue by sbatezat** [nestjs/graphql#2311]
### Did you read the migration guide?

- [X] I have read the whole migration guide

### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Versions

10.0.18 -> 10.0.20

### Describe the regression

I'm unable to launch nestjs application since the migration of @nestjs/graphql from 10.0.18 to 10.0.20
Stack trace:

```
Error: Cannot find module 'ts-morph'
Require stack:
- D:\app\node_modules\@nestjs\graphql\dist\graphql-ast.explorer.js
- D:\app\node_modules\@nestjs\graphql\dist\graphql.factory.js
- D:\app\node_modules\@nestjs\graphql\dist\drivers\abstract-graphql.driver.js
- D:\app\node_modules\@nestjs\graphql\dist\drivers\index.js
- D:\app\node_modules\@nestjs\graphql\dist\index.js
- D:\app\node_modules\@nestjs\apollo\dist\drivers\apollo-federation.driver.js
- D:\app\node_modules\@nestjs\apollo\dist\drivers\index.js
- D:\app\node_modules\@nestjs\apollo\dist\index.js
- D:\app\dist\application\app.module.js
- D:\app\dist\main.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (D:\app\node_modules\@nestjs\graphql\dist\graphql-ast.explorer.js:7:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

### Minimum reproduction code
My NPM dependencies :

```json
"dependencies": {
    "@n1ru4l/graphql-live-query": "0.9.0",
    "@n1ru4l/graphql-live-query-patch-json-patch": "0.6.1",
    "@n1ru4l/in-memory-live-query-store": "0.9.0",
    "@nestjs/apollo": "10.0.19",
    "@nestjs/axios": "0.1.0",
    "@nestjs/common": "8.4.7",
    "@nestjs/config": "2.2.0",
    "@nestjs/core": "8.4.7",
    "@nestjs/graphql": "10.0.20",
    "@nestjs/platform-express": "8.4.7",
    "apollo-server-express": "3.10.0",
    "bcryptjs": "2.4.3",
    "class-transformer": "0.5.1",
    "class-validator": "0.13.2",
    "compression": "1.7.4",
    "dataloader": "2.1.0",
    "email-templates": "10.0.0",
    "google-auth-library": "8.1.1",
    "graphql": "16.5.0",
    "graphql-parse-resolve-info": "4.12.3",
    "graphql-query-complexity": "0.11.0",
    "graphql-ws": "5.9.1",
    "jsonwebtoken": "8.5.1",
    "knex": "2.2.0",
    "nodemailer": "6.7.7",
    "pg": "8.7.3",
    "pug": "3.0.2",
    "reflect-metadata": "0.1.13",
    "subscriptions-transport-ws": "0.11.0"
  }
```

### Expected behavior

App is launching correctly without adding manually peer dependencies

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by kamilmysliwiec** [comment]
Fixed in 10.0.21, thanks for reporting!

**Comment by tanuck** [comment]
Hi. I'm still getting the same issue on v10.0.21.

**Comment by marmotz** [comment]
Hi. I'm still getting the same issue on v10.1.3.
